name: Deploy Frontend to Testserver

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install --force

      - name: Build Frontend
        run: npm run build

      - name: Debug dist folder
        run: ls -la ./dist

      # ✅ Accessibility-Check mit Lighthouse CI (non-blocking)
      - name: Install Serve and Lighthouse CI
        run: npm install -g serve @lhci/cli

      - name: Start local server
        run: |
          serve -s dist -l 5000 &
          sleep 5

      - name: Run Lighthouse CI (collect + report)
        run: |
          lhci collect --url=http://localhost:5000
          lhci report --output .lighthouseci
        continue-on-error: true

      - name: Inspect report files
        run: ls -la .lighthouseci

      - name: Upload Lighthouse Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci

      # 🔁 Deployment
      - name: Deploy via rsync to /var/www/
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          echo "🔁 Deployment nach: /var/www/"

          rsync -avzr --delete -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./dist/ $SSH_USER@$SSH_HOST:/var/www/
        env:
          SSH_KEY: ${{ secrets.TESTSERVER_SSH_KEY }}
          SSH_USER: ${{ secrets.TESTSERVER_USER }}
          SSH_HOST: ${{ secrets.TESTSERVER_HOST }}
