name: Deploy Frontend to Testserver

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install --force

      - name: Build Frontend
        run: npm run build

      - name: Debug dist folder
        run: ls -la ./dist

      - name: Deploy via rsync over SSH (preview-<reponame>)
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          TARGET_DIR="preview-$REPO_NAME"
          echo "🔁 Deployment nach: /var/www/$TARGET_DIR/"

          ssh -i deploy_key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "mkdir -p /var/www/$TARGET_DIR"

          rsync -avzr --delete -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" ./dist/ $SSH_USER@$SSH_HOST:/var/www/$TARGET_DIR/
        env:
          SSH_KEY: ${{ secrets.TESTSERVER_SSH_KEY }}
          SSH_USER: ${{ secrets.TESTSERVER_USER }}
          SSH_HOST: ${{ secrets.TESTSERVER_HOST }}
